config/routes.rb
Rails.application.routes.draw do
  # Users routes
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords"
  }

  # Nutritionists routes
  devise_for :nutritionists, controllers: {
    sessions: "nutritionists/sessions",
    registrations: "nutritionists/registrations",
    passwords: "nutritionists/passwords"
  }

  # Pages routes
  root to: "pages#home"
  get "/sign_in", to: "pages#sign_in", as: :sign_in
  get "/user_home", to: "pages#user_home", as: :user_home

  # In Body routes
  resources :in_bodies

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/in_body.rb
class InBody < ApplicationRecord
  # Callbacks
  before_save :calculate_indicators

  # Associations
  belongs_to :user
  belongs_to :nutritionist

  # Validations
  validates :user_id, presence: true
  validates :age, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :height, presence: true, numericality: { greater_than: 0, less_than: 3 }
  validates :weight, presence: true, numericality: { greater_than: 0 }
  validates :genre, presence: true
  validates :date, presence: true
  validates :body_water, :protein_mass, :minerals_mass, :body_fat, :lean_mass, :mass_free_of_fat, :muscle_mass, presence: true, numericality: { greater_than: 0 }

  private

  # Method to set the indicators of the in_body
  def calculate_indicators
    self.imc = (weight / (height * height)).round(2)
    self.percentage_body_fat = (body_fat / weight * 100).round(2)
    self.aec = (weight - mass_free_of_fat).round(2)
  end
end

app/controllers/in_bodies_controller.rb
class InBodiesController < ApplicationController
  skip_before_action :authenticate_user!, unless: :skip_authentication?
  before_action :set_users, only: %i[new create]
  before_action :set_genres, only: %i[new create]
  before_action :set_in_body, only: %i[show edit update destroy]

  def index
    @in_bodies = InBody.all
  end

  def show
  end

  def new
    @in_body = InBody.new
  end

  def create
    @in_body = InBody.new(in_body_params)
    @in_body.nutritionist = current_nutritionist
    if @in_body.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @in_body.update(in_body_params)
    redirect_to in_body_path(@in_body)
  end

  def destroy
    @in_body.destroy
    redirect_to in_body_path
  end

  private

  def in_body_params
    params.require(:in_body).permit(:weight, :height, :age, :genre, :date, :body_water, :protein_mass, :minerals_mass, :body_fat, :lean_mass, :mass_free_of_fat, :muscle_mass, :imc, :percentage_body_fat, :right_arm, :left_arm, :trunk, :right_leg, :left_leg, :aec, :user_id)
  end

  def set_users
    @users = User.all
  end

  def set_genres
    @genres = ["Masculino", "Femenino", "Otro", "Prefiero no decirlo"]
  end

  def set_in_body
    @in_body = InBody.find(params[:id])
  end

  def skip_authentication?
    return current_user && true
  end
end

app/views/in_bodies/_form.html.erb
<%= simple_form_for @in_body do |f| %>

  <%# Display errors messages %>
  <%= f.error_notification %>
  <%# Display errors messages %>

  <%# User data %>
  <div class="row">
    <h2>Información del paciente</h2>
  </div>
  <div class="row">
    <div class="col-12 col-lg-6">
      <% if @users %>
        <% @users.each do |user| %>
          <%= f.input :user_id, collection: User.all.map{ |patient| [patient.email, patient.id] }, label: "Selecciona un paciente" %>
        <% end %>
      <% else %>
        <%= f.input :user_id, label: "Selecciona un paciente", placeholder: "No hay usuarios" %>
      <% end %>
    </div>
    <div class="col-12 col-lg-6">
      <%= f.input :age, label: "Edad" %>
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-lg-6">
      <%= f.input :height, label: "Estatura (m)" %>
    </div>
    <div class="col-12 col-lg-6">
      <%= f.input :weight, label: "Peso (Kg)" %>
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-lg-6">
      <%= f.input :genre, collection: @genres, label: "Género" %>
    </div>
    <div class="col-12 col-lg-6">
      <%= f.input :date, as: :date, label: "Fecha" %>
    </div>
  </div>
  <%# User data %>

  <%# Body composition analysis %>
  <div class="row">
    <h2>Analisis composición corporal</h2>
  </div>
  <div class="row">
    <div class="col-12 col-lg-6">
      <%= f.input :body_water, label: "Agua corporal (Lt)" %>
    </div>
    <div class="col-12 col-lg-6">
      <%= f.input :protein_mass, label: "Proteína (Kg)" %>
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-lg-6">
      <%= f.input :minerals_mass, label: "Minerales (Kg)" %>
    </div>
    <div class="col-12 col-lg-6">
      <%= f.input :body_fat, label: "Grasa corporal (Kg)" %>
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-lg-6">
      <%= f.input :lean_mass, label: "Masa magra (Kg)" %>
    </div>
    <div class="col-12 col-lg-6">
      <%= f.input :mass_free_of_fat, label: "Masa libre de grasa (Kg)" %>
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-lg-6">
      <%= f.input :muscle_mass, label: "Masa muscular (Kg)" %>
    </div>
  </div>
  <%# Body composition analysis %>

  <%# Segement Analysis %>
  <div class="row">
    <h2>Análisis magro por segmentos</h2>
  </div>
  <div class="row">
    <div class="col-12 col-lg-6">
      <%= f.input :right_arm, label: "Brazo derecho (Kg)" %>
    </div>
    <div class="col-12 col-lg-6">
      <%= f.input :left_arm, label: "Brazo izquierdo (Kg)" %>
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-lg-6">
      <%= f.input :trunk, label: "Tronco (Kg)" %>
    </div>
    <div class="col-12 col-lg-6">
      <%= f.input :right_leg, label: "Pierna izquierda (Kg)" %>
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-lg-6">
      <%= f.input :left_leg, label: "Pierna derecha (Kg)" %>
    </div>
  </div>
  <%# Segement Analysis %>

  <%# Actions %>
  <div class="d-flex flex-row gap-2">
    <button class="btn btn-secondary rounded w-100">Volver</button>
    <%= f.submit "Añadir", class: "btn btn-primary rounded w-100" %>
  </div>
  <%# Actions %>

<% end %>

app/views/in_bodies/create.html.erb
<h1>InBodies#create</h1>
<p>Find me in app/views/in_bodies/create.html.erb</p>

app/views/in_bodies/edit.html.erb
<%= simple_form_for @in_body do |f| %>

  <%# Display errors messages %>
  <%= f.error_notification %>
  <%# Display errors messages %>

  <%# User data %>
  <div class="row">
    <h2>Información del paciente</h2>
  </div>
  <div class="row">
    <div class="col-12 col-lg-6">
      <% if @users %>
        <% @users.each do |user| %>
          <%= f.input :user_id, collection: User.all.map{ |patient| [patient.email, patient.id] }, label: "Selecciona un paciente" %>
        <% end %>
      <% else %>
        <%= f.input :user_id, label: "Selecciona un paciente", placeholder: "No hay usuarios" %>
      <% end %>
    </div>
    <div class="col-12 col-lg-6">
      <%= f.input :age, label: "Edad" %>
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-lg-6">
      <%= f.input :height, label: "Estatura (m)" %>
    </div>
    <div class="col-12 col-lg-6">
      <%= f.input :weight, label: "Peso (Kg)" %>
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-lg-6">
      <%= f.input :genre, collection: @genres, label: "Género" %>
    </div>
    <div class="col-12 col-lg-6">
      <%= f.input :date, as: :date, label: "Fecha" %>
    </div>
  </div>
  <%# User data %>

  <%# Body composition analysis %>
  <div class="row">
    <h2>Analisis composición corporal</h2>
  </div>
  <div class="row">
    <div class="col-12 col-lg-6">
      <%= f.input :body_water, label: "Agua corporal (Lt)" %>
    </div>
    <div class="col-12 col-lg-6">
      <%= f.input :protein_mass, label: "Proteína (Kg)" %>
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-lg-6">
      <%= f.input :minerals_mass, label: "Minerales (Kg)" %>
    </div>
    <div class="col-12 col-lg-6">
      <%= f.input :body_fat, label: "Grasa corporal (Kg)" %>
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-lg-6">
      <%= f.input :lean_mass, label: "Masa magra (Kg)" %>
    </div>
    <div class="col-12 col-lg-6">
      <%= f.input :mass_free_of_fat, label: "Masa libre de grasa (Kg)" %>
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-lg-6">
      <%= f.input :muscle_mass, label: "Masa muscular (Kg)" %>
    </div>
  </div>
  <%# Body composition analysis %>

  <%# Segement Analysis %>
  <div class="row">
    <h2>Análisis magro por segmentos</h2>
  </div>
  <div class="row">
    <div class="col-12 col-lg-6">
      <%= f.input :right_arm, label: "Brazo derecho (Kg)" %>
    </div>
    <div class="col-12 col-lg-6">
      <%= f.input :left_arm, label: "Brazo izquierdo (Kg)" %>
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-lg-6">
      <%= f.input :trunk, label: "Tronco (Kg)" %>
    </div>
    <div class="col-12 col-lg-6">
      <%= f.input :right_leg, label: "Pierna izquierda (Kg)" %>
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-lg-6">
      <%= f.input :left_leg, label: "Pierna derecha (Kg)" %>
    </div>
  </div>
  <%# Segement Analysis %>

  <%# Actions %>
  <div class="d-flex flex-row gap-2">
    <button class="btn btn-secondary rounded w-100">Volver</button>
    <%= f.submit "Guardar", class: "btn btn-primary rounded w-100" %>
  </div>
  <%# Actions %>

<% end %>

app/views/in_bodies/index.html.erb
<div class="row justify-content-between">
  <div class="col-6">
    <h1> Lista de InBodys </h1>
  </div>
  <div class="col-6 text-end">
    <%= link_to "Nuevo", new_in_body_path, class: "btn btn-primary" %>
  </div>
</div>

<%= render(InBody::TableComponent.new(data: @in_bodies)) %>

app/views/in_bodies/new.html.erb
<%= simple_form_for @in_body do |f| %>

  <%# Display errors messages %>
  <%= f.error_notification %>
  <%# Display errors messages %>

  <%# User data %>
  <div class="row">
    <h2>Información del paciente</h2>
  </div>
  <div class="row">
    <div class="col-12 col-lg-6">
      <% if @users %>
        <% @users.each do |user| %>
          <%= f.input :user_id, collection: User.all.map{ |patient| [patient.email, patient.id] }, label: "Selecciona un paciente" %>
        <% end %>
      <% else %>
        <%= f.input :user_id, label: "Selecciona un paciente", placeholder: "No hay usuarios" %>
      <% end %>
    </div>
    <div class="col-12 col-lg-6">
      <%= f.input :age, label: "Edad" %>
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-lg-6">
      <%= f.input :height, label: "Estatura (m)" %>
    </div>
    <div class="col-12 col-lg-6">
      <%= f.input :weight, label: "Peso (Kg)" %>
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-lg-6">
      <%= f.input :genre, collection: @genres, label: "Género" %>
    </div>
    <div class="col-12 col-lg-6">
      <%= f.input :date, as: :date, label: "Fecha" %>
    </div>
  </div>
  <%# User data %>

  <%# Body composition analysis %>
  <div class="row">
    <h2>Analisis composición corporal</h2>
  </div>
  <div class="row">
    <div class="col-12 col-lg-6">
      <%= f.input :body_water, label: "Agua corporal (Lt)" %>
    </div>
    <div class="col-12 col-lg-6">
      <%= f.input :protein_mass, label: "Proteína (Kg)" %>
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-lg-6">
      <%= f.input :minerals_mass, label: "Minerales (Kg)" %>
    </div>
    <div class="col-12 col-lg-6">
      <%= f.input :body_fat, label: "Grasa corporal (Kg)" %>
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-lg-6">
      <%= f.input :lean_mass, label: "Masa magra (Kg)" %>
    </div>
    <div class="col-12 col-lg-6">
      <%= f.input :mass_free_of_fat, label: "Masa libre de grasa (Kg)" %>
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-lg-6">
      <%= f.input :muscle_mass, label: "Masa muscular (Kg)" %>
    </div>
  </div>
  <%# Body composition analysis %>

  <%# Segement Analysis %>
  <div class="row">
    <h2>Análisis magro por segmentos</h2>
  </div>
  <div class="row">
    <div class="col-12 col-lg-6">
      <%= f.input :right_arm, label: "Brazo derecho (Kg)" %>
    </div>
    <div class="col-12 col-lg-6">
      <%= f.input :left_arm, label: "Brazo izquierdo (Kg)" %>
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-lg-6">
      <%= f.input :trunk, label: "Tronco (Kg)" %>
    </div>
    <div class="col-12 col-lg-6">
      <%= f.input :right_leg, label: "Pierna izquierda (Kg)" %>
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-lg-6">
      <%= f.input :left_leg, label: "Pierna derecha (Kg)" %>
    </div>
  </div>
  <%# Segement Analysis %>

  <%# Actions %>
  <div class="d-flex flex-row gap-2">
    <button class="btn btn-secondary rounded w-100">Volver</button>
    <%= f.submit "Añadir", class: "btn btn-primary rounded w-100" %>
  </div>
  <%# Actions %>

<% end %>

app/views/in_bodies/show.html.erb
<div class="row">
  <div class="col-12 col-lg-4">

    <%# Card with pacient info %>
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"> <strong>Información del paciente</strong></h5>
        <ul>
          <li><strong>Nombre:</strong> <%= @in_body.user.email || "Sin nombre" %></li>
          <li><strong>Edad:</strong> <%= @in_body.age %></li>
          <li><strong>Altura:</strong> <%= @in_body.height %> m</li>
          <li><strong>Peso:</strong> <%= @in_body.weight %> Kg</li>
          <li><strong>Género:</strong> <%= @in_body.genre %></li>
        </ul>
      </div>
    </div>
    <%# Card with pacient info %>

  </div>
  <div class="col-12 col-lg-4">

    <%# Card with body composition %>
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"> <strong>Análisis composición corporal</strong></h5>
        <ul>
          <li><strong>Agua corporal:</strong> <%= @in_body.body_water %> Lt</li>
          <li><strong>Masa proteína:</strong> <%= @in_body.protein_mass %> Kg</li>
          <li><strong>Masa minerales:</strong> <%= @in_body.minerals_mass %> Kg</li>
          <li><strong>Agua corporal:</strong> <%= @in_body.body_water %> Kg</li>
          <li><strong>Grasa corporal:</strong> <%= @in_body.body_fat %> Kg</li>
          <li><strong>Masa magra:</strong> <%= @in_body.lean_mass %> Kg</li>
          <li><strong>Masa libre de grasa:</strong> <%= @in_body.mass_free_of_fat %> Kg</li>
          <li><strong>Masa muscular:</strong> <%= @in_body.muscle_mass %> Kg</li>
        </ul>
      </div>
    </div>
    <%# Card with body composition %>

  </div>

  <div class="col-12 col-lg-4">

    <%# Card with segment analysis %>
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"> <strong>Análisis por segemento</strong></h5>
        <ul>
          <li><strong>Brazo derecho:</strong> <%= @in_body.right_arm %> Kg</li>
          <li><strong>Brazo izquierdo:</strong> <%= @in_body.left_arm %> Kg</li>
          <li><strong>Pierna derecha:</strong> <%= @in_body.right_leg %> Kg</li>
          <li><strong>Pierna izquierda:</strong> <%= @in_body.left_leg %> Kg</li>
          <li><strong>Tronco:</strong> <%= @in_body.trunk %> Kg</li>
        </ul>
      </div>
    </div>
    <%# Card with segment analysis %>

  </div>
</div>

<div class="row">
  <div class="col-12 col-4">

    <%# Card with indicators %>
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"> <strong>Análisis por segemento</strong></h5>
        <ul>
          <li><strong>IMC:</strong> <%= @in_body.imc %> Kg/m2</li>
          <li><strong>Porcentaje grasa corporal</strong> <%= @in_body.percentage_body_fat %> %</li>
          <li><strong>AEC</strong> <%= @in_body.aec %></li>
        </ul>
      </div>
    </div>
    <%# Card with indicators %>

  </div>
</div>