config/routes.rb
Rails.application.routes.draw do
  # Users routes
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords"
  }

  # Nutritionists routes
  devise_for :nutritionists, controllers: {
    sessions: "nutritionists/sessions",
    registrations: "nutritionists/registrations",
    passwords: "nutritionists/passwords"
  }

  # Pages routes
  root to: "pages#home"
  get "/sign_in", to: "pages#sign_in", as: :sign_in
  get "/user_home", to: "pages#user_home", as: :user_home

  # In Body routes
  resources :in_bodies

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if nutritionist_signed_in? || user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out 1", destroy_nutritionist_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              <%= link_to "Log out 2", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Ingresar", sign_in_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_nutritionist_sidebar.html.erb
<div class="container">

  <div class="d-flex justify-content-center my-3 gap-2">
    <%= link_to "InBody", in_bodies_path, class: "btn btn-primary" %>
    <%= link_to "Cerrar sesión", destroy_nutritionist_session_path, data: {turbo_method: :delete}, class: "btn btn-danger" %>
  </div>

</div>

app/views/shared/_user_sidebar.html.erb
<div class="container">

  <div class="d-flex justify-content-center my-3 gap-2">
    <button class="btn btn-primary"> Progreso </button>
    <%= link_to "InBody", in_bodies_index_path, class: "btn btn-primary" %>
    <button class="btn btn-primary"> Pautas </button>
    <button class="btn btn-primary"> Meal helper </button>
    <button class="btn btn-primary"> Personal info </button>
    <%= link_to "Cerrar sesión", destroy_user_session_path, data: {turbo_method: :delete}, class: "btn btn-danger" %>
  </div>

</div>