config/routes.rb
Rails.application.routes.draw do
  # Users routes
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords"
  }

  # Nutritionists routes
  devise_for :nutritionists, controllers: {
    sessions: "nutritionists/sessions",
    registrations: "nutritionists/registrations",
    passwords: "nutritionists/passwords"
  }

  # Pages routes
  root to: "pages#home"
  get "/sign_in", to: "pages#sign_in", as: :sign_in
  get "/user_home", to: "pages#user_home", as: :user_home

  # In Body routes
  resources :in_bodies

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMealMaster</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%# Render Nutritionist Sidebar %>
    <% if current_nutritionist %>
      <%= render "shared/nutritionist_sidebar" %>

    <%# Render Patiente/User Sidebar %>
    <% elsif current_user %>
      <%= render "shared/user_sidebar" %>

    <%# Render HomePage %>
    <% else %>
      <%= render "shared/navbar" %>
    <% end %>
    <%= render "shared/flashes" %>

    <%# Render the content %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>